FUGLE_API_KEY = "NDE5NjA5ZWUtNjhlZS00OGFjLWI4ZTAtNmQxMTViMGM5Mjk1IDJiNTE4MTIxLTIyMGMtNDY0OS05MWYwLWM3ZDM0YzBjN2FhYQ=="
ALPACA_API_KEY = "PKUGA5L6FFG5NLHE5MQBOY5X4D"
ALPACA_SECRET_KEY = "3PgkyaqGL2W3RotDFVi9CAdyjyje1Pvdy973ipGi37t7"
